# permissions for end users to edit uniteddeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: uniteddeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kruise
    app.kubernetes.io/part-of: kruise
    app.kubernetes.io/managed-by: kustomize
  name: uniteddeployment-editor-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - uniteddeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - uniteddeployments/status
  verbs:
  - get
