# permissions for end users to edit podunavailablebudgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podunavailablebudget-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kruise
    app.kubernetes.io/part-of: kruise
    app.kubernetes.io/managed-by: kustomize
  name: podunavailablebudget-editor-role
rules:
- apiGroups:
  - policy.kruise.io
  resources:
  - podunavailablebudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.kruise.io
  resources:
  - podunavailablebudgets/status
  verbs:
  - get
