apiVersion: apps.kruise.io/v1beta1
kind: ResourceDistribution
metadata:
  labels:
    app.kubernetes.io/name: resourcedistribution
    app.kubernetes.io/instance: resourcedistribution-sample
    app.kubernetes.io/part-of: kruise
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kruise
  name: resourcedistribution-sample
spec:
  # TODO(user): Add fields here
