apiVersion: apps.kruise.io/v1beta1
kind: UnitedDeployment
metadata:
  labels:
    app.kubernetes.io/name: uniteddeployment
    app.kubernetes.io/instance: uniteddeployment-sample
    app.kubernetes.io/part-of: kruise
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kruise
  name: uniteddeployment-sample
spec:
  # TODO(user): Add fields here
