apiVersion: apps.kruise.io/v1beta1
kind: AdvancedCronJob
metadata:
  labels:
    app.kubernetes.io/name: advancedcronjob
    app.kubernetes.io/instance: advancedcronjob-sample
    app.kubernetes.io/part-of: kruise
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kruise
  name: advancedcronjob-sample
spec:
  # TODO(user): Add fields here
